export const S = {
  section: {
    padding: "0 24px",
    color: "var(--text-primary, var(--text-color, #f8fafc))",
    "text-shadow": "none",
  },
  toolbar: {
    display: "flex",
    "align-items": "center",
    gap: "10px",
    padding: "12px 0",
    "flex-wrap": "wrap" as const,
    color: "var(--text-primary, var(--text-color, #f8fafc))",
    "text-shadow": "none",
  },
  branchBadge: {
    display: "inline-flex",
    "align-items": "center",
    gap: "6px",
    padding: "4px 12px",
    background: "rgba(255, 255, 255, 0.08)",
    color: "var(--text-primary, #f8fafc)",
    border: "1px solid rgba(255, 255, 255, 0.15)",
    "border-radius": "999px",
    "font-size": "12px",
    "font-weight": 600,
    "font-family": "Space Mono, monospace" as const,
    "box-shadow": "0 2px 8px rgba(0, 0, 0, 0.2)",
    "backdrop-filter": "blur(8px)",
  },
  badge: {
    display: "inline-flex",
    "align-items": "center",
    gap: "4px",
    padding: "3px 8px",
    "border-radius": "6px",
    "font-size": "11px",
    "font-weight": 600,
    "font-family": "Space Mono, monospace",
    "text-shadow": "none",
    "line-height": 1.2,
  },
  stagedBadge: {
    background: "var(--badge-bg, rgba(255, 255, 255, 0.08))",
    color: "var(--badge-text, #e2e8f0)",
    border: "1px solid var(--badge-border, rgba(255, 255, 255, 0.15))",
  },
  unstagedBadge: {
    background: "rgba(255, 255, 255, 0.06)",
    color: "var(--text-secondary, #cbd5e1)",
    border: "1px solid rgba(255, 255, 255, 0.12)",
  },
  untrackedBadge: {
    background: "rgba(255, 255, 255, 0.05)",
    color: "var(--text-muted, #94a3b8)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
  },
  btn: {
    display: "inline-flex",
    "align-items": "center",
    "justify-content": "center",
    gap: "6px",
    padding: "6px 14px",
    "font-size": "12px",
    "border-radius": "8px",
    border: "1px solid rgba(255, 255, 255, 0.12)",
    cursor: "pointer",
    "font-weight": 600,
    "font-family": "var(--fluent-font, system-ui, -apple-system, sans-serif)",
    transition: "all 0.15s ease",
    outline: "none",
    "user-select": "none" as const,
  } as any,
  btnPrimary: {
    background: "var(--btn-primary-bg, #1e293b)",
    color: "var(--btn-primary-text, #f8fafc)",
    border: "1px solid rgba(255, 255, 255, 0.18)",
    "box-shadow": "0 2px 8px rgba(0, 0, 0, 0.25)",
  },
  btnSecondary: {
    background: "var(--btn-secondary-bg, rgba(255, 255, 255, 0.05))",
    color: "var(--btn-secondary-text, #cbd5e1)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    "backdrop-filter": "blur(8px)",
  },
  btnDanger: {
    background: "var(--btn-danger-bg, rgba(153, 27, 27, 0.3))",
    color: "var(--btn-danger-text, #fca5a5)",
    border: "1px solid rgba(239, 68, 68, 0.3)",
  },
  card: {
    background: "var(--card-bg, rgba(15, 23, 42, 0.55))",
    border: "1px solid var(--card-border, rgba(255, 255, 255, 0.08))",
    "box-shadow": "0 4px 16px rgba(0, 0, 0, 0.18)",
    "backdrop-filter": "blur(16px)",
    "-webkit-backdrop-filter": "blur(16px)",
    "border-radius": "12px",
    padding: "16px",
    "margin-bottom": "12px",
  },
  toolsMenuItem: {
    display: "flex",
    "align-items": "center",
    gap: "8px",
    width: "100%",
    padding: "8px 10px",
    "font-size": "12.5px",
    "font-weight": 500,
    color: "#f8fafc",
    background: "rgba(255, 255, 255, 0.04)",
    border: "none",
    "border-radius": "6px",
    cursor: "pointer",
    "text-align": "left" as const,
    transition: "all 0.15s ease",
  },
  fileRow: {
    display: "flex",
    "align-items": "center",
    "justify-content": "space-between",
    padding: "8px 12px",
    "border-bottom": "1px solid rgba(255, 255, 255, 0.05)",
    "font-size": "13px",
    color: "var(--text-primary, var(--text-color, #f8fafc))",
    "text-shadow": "none",
    "border-radius": "6px",
    transition: "background 0.15s ease",
  },
  commitInput: {
    width: "100%",
    padding: "10px 14px",
    "border-radius": "8px",
    border: "1px solid rgba(255, 255, 255, 0.12)",
    background: "var(--input-bg, rgba(0, 0, 0, 0.35))",
    color: "var(--text-primary, var(--text-color, #f8fafc))",
    "font-size": "13.5px",
    "box-sizing": "border-box" as const,
    "font-family": "var(--fluent-font, system-ui, -apple-system, sans-serif)",
    outline: "none",
    transition: "border-color 0.2s",
  },
  statusMsg: {
    padding: "10px 14px",
    "border-radius": "8px",
    "font-size": "12.5px",
    "margin-bottom": "8px",
    "backdrop-filter": "blur(8px)",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    background: "rgba(var(--panel-rgb, 10, 14, 23), 0.35)",
  },
  tab: {
    display: "inline-flex",
    "align-items": "center",
    gap: "6px",
    padding: "8px 16px",
    "font-size": "12.5px",
    "font-weight": 600,
    cursor: "pointer",
    color: "var(--text-secondary, #94a3b8)",
    "border-bottom": "2px solid transparent",
    "white-space": "nowrap" as const,
    transition: "all 0.15s ease",
    "user-select": "none" as const,
  },
  tabActive: {
    color: "var(--text-primary, #ffffff)",
    "border-bottom-color": "var(--accent-default, #e2e8f0)",
    background: "rgba(255, 255, 255, 0.06)",
  },
  tabBar: {
    display: "flex",
    gap: "2px",
    "border-bottom": "1px solid rgba(255, 255, 255, 0.08)",
    overflow: "auto",
    "flex-shrink": 0,
    background: "rgba(var(--panel-rgb, 10, 14, 23), 0.35)",
    "backdrop-filter": "blur(12px)",
    padding: "0 12px",
  },
  input: {
    padding: "8px 12px",
    "border-radius": "8px",
    border: "1px solid rgba(255, 255, 255, 0.12)",
    background: "var(--input-bg, rgba(0, 0, 0, 0.35))",
    color: "var(--text-primary, var(--text-color, #f8fafc))",
    "font-size": "13px",
    "box-sizing": "border-box" as const,
    "font-family": "var(--fluent-font, system-ui, -apple-system, sans-serif)",
    outline: "none",
    transition: "border-color 0.2s",
  },
  select: {
    padding: "8px 12px",
    "border-radius": "8px",
    border: "1px solid rgba(255, 255, 255, 0.12)",
    background: "var(--input-bg, rgba(0, 0, 0, 0.35))",
    color: "var(--text-primary, var(--text-color, #f8fafc))",
    "font-size": "13px",
    "font-family": "var(--fluent-font, system-ui, -apple-system, sans-serif)",
    outline: "none",
    cursor: "pointer",
  },
  diffAdded: {
    background: "rgba(52, 211, 153, 0.1)",
    color: "#34d399",
    "border-left": "3px solid #34d399",
  },
  diffRemoved: {
    background: "rgba(248, 113, 113, 0.1)",
    color: "#f87171",
    "border-left": "3px solid #f87171",
  },
  diffContext: {
    background: "transparent",
    color: "var(--text-primary, var(--text-color, #f8fafc))",
    "border-left": "3px solid transparent",
  },
  diffHunkHeader: {
    background: "rgba(255, 255, 255, 0.06)",
    color: "#e2e8f0",
    "font-family": "Space Mono, monospace",
    "font-size": "11.5px",
    padding: "5px 10px",
    "font-weight": 600,
    border: "1px solid rgba(255, 255, 255, 0.12)",
    "border-radius": "4px",
    margin: "6px 0",
  },
  diffLine: {
    display: "flex",
    "font-family": "Space Mono, monospace",
    "font-size": "12px",
    "line-height": "22px",
    padding: "0 10px",
  },
  diffGutter: {
    display: "inline-block",
    width: "44px",
    "text-align": "right" as const,
    "padding-right": "10px",
    color: "rgba(255, 255, 255, 0.35)",
    "user-select": "none" as const,
    "border-right": "1px solid rgba(255, 255, 255, 0.08)",
    "margin-right": "8px",
  },
  graphRow: {
    display: "flex",
    "align-items": "center",
    padding: "6px 0",
    gap: "12px",
    "font-size": "13px",
    color: "var(--text-primary, var(--text-color, #f8fafc))",
  },
  graphDot: {
    "border-radius": "50%",
    width: "10px",
    height: "10px",
    "flex-shrink": 0,
  },
  cardHeader: {
    display: "flex",
    "align-items": "center",
    "justify-content": "space-between",
    margin: "0 0 12px",
    "font-size": "14px",
    "font-weight": 600,
    color: "var(--text-primary, var(--text-color, #f8fafc))",
  },
  emptyState: {
    "text-align": "center" as const,
    color: "var(--text-secondary, #94a3b8)",
    "font-size": "14px",
    padding: "48px 0",
  },
  repoCard: {
    display: "flex",
    "align-items": "center",
    gap: "14px",
    padding: "14px 18px",
    background: "var(--card-bg, rgba(15, 23, 42, 0.55))",
    border: "1px solid var(--card-border, rgba(255, 255, 255, 0.08))",
    "box-shadow": "0 4px 16px rgba(0, 0, 0, 0.15)",
    "backdrop-filter": "blur(12px)",
    "-webkit-backdrop-filter": "blur(12px)",
    "border-radius": "10px",
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  sectionTitle: {
    margin: "0 0 12px",
    "font-size": "14px",
    "font-weight": 700,
    color: "var(--text-primary, var(--text-color, #f8fafc))",
    "letter-spacing": "0.3px",
  },
  toast: {
    position: "fixed" as const,
    bottom: "20px",
    left: "50%",
    transform: "translateX(-50%)",
    padding: "10px 24px",
    "border-radius": "10px",
    "font-size": "13px",
    "font-weight": 600,
    "z-index": 9999,
    transition: "all 0.2s cubic-bezier(0.22, 1, 0.36, 1)",
    "box-shadow": "0 10px 30px rgba(0, 0, 0, 0.5)",
    "backdrop-filter": "blur(16px)",
  },
  toastSuccess: {
    background: "rgba(30, 41, 59, 0.95)",
    color: "#f8fafc",
    border: "1px solid rgba(255, 255, 255, 0.2)",
  },
  toastError: {
    background: "rgba(153, 27, 27, 0.95)",
    color: "#ffffff",
    border: "1px solid rgba(239, 68, 68, 0.5)",
  },
  toastInfo: {
    background: "rgba(30, 41, 59, 0.95)",
    color: "#cbd5e1",
    border: "1px solid rgba(255, 255, 255, 0.2)",
  },
  statusBar: {
    height: "28px",
    background: "rgba(var(--panel-rgb, 10, 14, 23), 0.45)",
    "backdrop-filter": "blur(16px)",
    "-webkit-backdrop-filter": "blur(16px)",
    "border-top": "1px solid rgba(255, 255, 255, 0.08)",
    padding: "0 16px",
    display: "flex",
    "align-items": "center",
    "justify-content": "space-between",
    "font-size": "11px",
    "font-family": "Space Mono, monospace",
    color: "var(--text-secondary, #94a3b8)",
    "flex-shrink": 0,
    "user-select": "none" as const,
    "z-index": 100,
  },
  conventionalChip: {
    padding: "3px 8px",
    "border-radius": "6px",
    "font-size": "11px",
    "font-family": "Space Mono, monospace",
    "font-weight": 600,
    cursor: "pointer",
    background: "rgba(255, 255, 255, 0.05)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    color: "var(--text-secondary, #94a3b8)",
    transition: "all 0.15s ease",
    "user-select": "none" as const,
  },
};
