export const S = {
  section: { padding: "0 24px" },
  toolbar: { display: "flex", "align-items": "center", gap: "12px", padding: "12px 0", "flex-wrap": "wrap" as const },
  branchBadge: { display: "flex", "align-items": "center", gap: "6px", padding: "5px 12px", background: "var(--accent-color, #f59e0b)", color: "#000", "border-radius": "20px", "font-size": "13px", "font-weight": 600, "font-family": "Space Mono, monospace" as const },
  badge: { padding: "4px 10px", "border-radius": "4px", "font-size": "11px", "font-weight": 600 },
  stagedBadge: { background: "rgba(34,197,94,0.2)", color: "#4ade80" },
  unstagedBadge: { background: "rgba(59,130,246,0.2)", color: "#60a5fa" },
  untrackedBadge: { background: "rgba(239,68,68,0.2)", color: "#f87171" },
  btn: { padding: "6px 14px", "font-size": "12px", "border-radius": "6px", border: "none", cursor: "pointer", "font-weight": 600 } as any,
  btnPrimary: { background: "var(--accent-color, #f59e0b)", color: "#000" },
  btnSecondary: { background: "rgba(255,255,255,0.1)", color: "var(--text-color)" },
  btnDanger: { background: "rgba(239,68,68,0.2)", color: "#f87171", border: "1px solid rgba(239,68,68,0.3)" },
  card: { background: "var(--panel-bg)", border: "1px solid var(--border-strong)", "border-radius": "8px", padding: "16px", "margin-bottom": "12px" },
  fileRow: { display: "flex", "align-items": "center", "justify-content": "space-between", padding: "6px 0", "border-bottom": "1px solid var(--border-subtle, rgba(255,255,255,0.04))", "font-size": "13px" },
  commitInput: { width: "100%", padding: "8px 12px", "border-radius": "6px", border: "1px solid var(--border-strong)", background: "var(--bg-color, #1a1a2e)", color: "var(--text-color)", "font-size": "14px", "box-sizing": "border-box" as const },
  statusMsg: { padding: "8px 12px", "border-radius": "6px", "font-size": "13px", "margin-bottom": "8px" },
  tab: { display: "flex", "align-items": "center", gap: "6px", padding: "8px 14px", "font-size": "12px", "font-weight": 500, cursor: "pointer", color: "var(--text-muted, #888)", "border-bottom": "2px solid transparent", "white-space": "nowrap" as const, transition: "color 0.15s, border-color 0.15s" },
  tabActive: { color: "var(--text-color)", "border-bottom-color": "var(--accent-color, #f59e0b)" },
  tabBar: { display: "flex", "gap": "0", "border-bottom": "1px solid var(--border-strong)", overflow: "auto", "flex-shrink": 0 },
  input: { padding: "8px 12px", "border-radius": "6px", border: "1px solid var(--border-strong)", background: "var(--bg-color, #1a1a2e)", color: "var(--text-color)", "font-size": "13px", "box-sizing": "border-box" as const },
  select: { padding: "8px 12px", "border-radius": "6px", border: "1px solid var(--border-strong)", background: "var(--bg-color, #1a1a2e)", color: "var(--text-color)", "font-size": "13px" },
  diffAdded: { background: "rgba(34,197,94,0.08)", color: "#4ade80", "border-left": "3px solid #4ade80" },
  diffRemoved: { background: "rgba(239,68,68,0.08)", color: "#f87171", "border-left": "3px solid #f87171" },
  diffContext: { background: "transparent", color: "var(--text-color)", "border-left": "3px solid transparent" },
  diffHunkHeader: { background: "rgba(255,255,255,0.05)", color: "var(--text-muted, #888)", "font-family": "Space Mono, monospace", "font-size": "12px", padding: "4px 8px" },
  diffLine: { display: "flex", "font-family": "Space Mono, monospace", "font-size": "12px", "line-height": "20px", padding: "0 8px" },
  diffGutter: { display: "inline-block", width: "40px", "text-align": "right" as const, "padding-right": "8px", color: "var(--text-muted, #888)", "user-select": "none" as const },
  graphRow: { display: "flex", "align-items": "center", padding: "4px 0", gap: "12px", "font-size": "13px" },
  graphDot: { "border-radius": "50%", width: "10px", height: "10px", "flex-shrink": 0 },
  cardHeader: { display: "flex", "align-items": "center", "justify-content": "space-between", margin: "0 0 10px", "font-size": "14px", "font-weight": 600 },
  emptyState: { "text-align": "center" as const, color: "var(--text-muted, #888)", "font-size": "14px", padding: "40px 0" },
  repoCard: { display: "flex", "align-items": "center", gap: "12px", padding: "14px 16px", background: "var(--panel-bg)", border: "1px solid var(--border-strong)", "border-radius": "8px", cursor: "pointer", transition: "border-color 0.15s" },
  sectionTitle: { margin: "0 0 10px", "font-size": "14px", "font-weight": 600 },
  toast: { position: "fixed" as const, bottom: "16px", left: "50%", transform: "translateX(-50%)", padding: "8px 20px", "border-radius": "6px", "font-size": "13px", "font-weight": 500, "z-index": 9999, transition: "opacity 0.3s" },
  toastSuccess: { background: "rgba(34,197,94,0.9)", color: "#000" },
  toastError: { background: "rgba(239,68,68,0.9)", color: "#fff" },
};
